title: A github:pages Blog
tagline: github:pages is great!
owner: Jun Ki Lee
link: https://github.com/christopherpoole/ghpblog
copyright: Copyright Jun Ki Lee 2015


pygments: true
permalink: '/:title'
markdown: rdiscount

exclude: [README.md]

