title: Jun Ki Lee
tagline: Blog and Portfolio Pages
owner: Jun Ki Lee
link: http://junkilee.github.io
copyright: Copyright Jun Ki Lee 2015


permalink: '/:title'
markdown: kramdown
highlighter: pygments

#kramdown:
#    input: GFM
#    syntax_highlighter: rouge

exclude: [README.md]

