title: Jun Ki Lee
tagline: Blog and Portfolio Pages
owner: Jun Ki Lee
link: http://junkilee.github.io
copyright: Copyright Jun Ki Lee 2015


highlighter: true
permalink: '/:title'
markdown: kramdown

exclude: [README.md]

